"""
Applies cellpose algorithms to determine cellular and nuclear masks
"""

# used napari-fast environment

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from cellpose import models
from cellpose import plot, utils
from skimage import filters
from skimage.transform import resize
from loguru import logger
from cellpose.io import logger_setup

logger_setup()

logger.info("import ok")

image_folder = "results/initial_cleanup/"
output_folder = "results/cellpose_masking/"

if not os.path.exists(output_folder):
    os.mkdir(output_folder)


def apply_cellpose(
    images,
    image_type="sam",
    diameter=None,
    flow_threshold=0.4,
    cellprob_threshold=0.0,
    niter=None,
    use_gpu=True,
    big_images=False,
):
    """
    Apply cellpose to a list of images.

    Return the masks, flows, and styles generated by the cellpose model.

    Args:
        images (np.array):
            Input images. Each image should be a numpy array with shape
            (channels, height, width).

        image_type (str, optional):
            Type of cellpose model to use. Defaults to "sam".

        diameter (int, optional):
            Diameter of cells to be detected. Defaults to None.

        flow_threshold (float, optional):
            Threshold for flow. Defaults to 0.4.

        cellprob_threshold (float, optional):
            Threshold for cell probability. Defaults to 0.0.

        niter (int, optional):
            Number of iterations. Increase for long cells.
            Defaults to None.

        use_gpu (bool, optional):
            Whether or not to use GPU for processing.
            Defaults to True.

        big_images (bool, optional):
            Whether images should first be resized to 1024 x 1024.
            Defaults to False.

    Returns:
        tuple:
            masks, flows, styles
    """

    model = models.CellposeModel(
        model_type=image_type,
        gpu=use_gpu,
    )

    images = [
        img.astype(np.uint16)
        for img in images
    ]

    if big_images == True:

        # Sizes for resizing
        smol_size = (1024, 1024)

        # Keep the original size for each image.
        original_sizes = [
            img.shape[1:]
            for img in images
        ]

        # Resize images
        resized_images = []

        for img in images:
            smol_arrs = []

            for ch in range(0, np.shape(img)[0]):
                smol_arrs.append(
                    resize(
                        img[ch],
                        smol_size,
                        preserve_range=True,
                    ).astype(np.uint16)
                )

            resized_images.append(
                np.stack(
                    smol_arrs,
                    axis=0,
                )
            )

        images = resized_images

        # Apply cellpose to resized images
        masks, flows, styles = model.eval(
            images,
            diameter=diameter,
            flow_threshold=flow_threshold,
            cellprob_threshold=cellprob_threshold,
            niter=niter,
        )

        # Resize masks to original size
        resized_masks = []

        for mask_index, mask in enumerate(masks):
            orig_size = original_sizes[mask_index]

            # Cellpose masks are 2D arrays:
            # (height, width)
            #
            # The original code incorrectly looped through mask.shape[0],
            # which treated each image row as if it were a channel.
            resized_mask = resize(
                mask,
                orig_size,
                order=0,
                preserve_range=True,
                anti_aliasing=False,
            ).astype(np.int32)

            resized_masks.append(resized_mask)

        masks = resized_masks

        # Resize flows to original size
        resized_flows = []

        for flow_index, flow in enumerate(flows):
            orig_size = original_sizes[flow_index]

            # OpenCV expects:
            # (width, height)
            #
            # while orig_size is:
            # (height, width)
            resized_flow = cv2.resize(
                flow[0],
                (
                    orig_size[1],
                    orig_size[0],
                ),
            )

            resized_flows.append(resized_flow)

        flows = resized_flows

    else:
        masks, flows, styles = model.eval(
            images,
            diameter=diameter,
            flow_threshold=flow_threshold,
            cellprob_threshold=cellprob_threshold,
            niter=niter,
        )

    return masks, flows, styles


def visualise_cell_pose(
    images,
    masks,
    flows,
    big_images=False,
):
    """
    Visualise the results of cellpose on a list of images, masks, and flows.

    Args:
        images (list):
            List of numpy arrays. Each image should have shape
            (channels, height, width).

        masks (list):
            List of 2D Cellpose masks. Each mask should have shape
            (height, width).

        flows (list):
            List of flow fields.

        big_images (bool, optional):
            Whether the images were resized before Cellpose.
            Defaults to False.
    """

    for idx, image in enumerate(images):

        fig, ax = plt.subplots(
            1,
            4,
            figsize=(12, 4),
        )

        ax[0].imshow(
            image[0],
            cmap="gray_r",
        )

        ax[0].set_title("original")

        # Plot flow fields
        if big_images:
            flow = flows[idx]
        else:
            flow = flows[idx][0]

        ax[1].imshow(flow)
        ax[1].set_title("flows")

        # Outlines
        #
        # Each mask is already 2D, so do not use masks[idx][0].
        outlines = utils.outlines_list(
            masks[idx]
        )

        ax[2].imshow(
            image[0],
            cmap="gray",
        )

        for o in outlines:

            # outlines_list returns coordinates as:
            # x, y
            ax[2].plot(
                o[:, 0],
                o[:, 1],
                color="r",
            )

        ax[2].set_title("outlines")

        # Mask overlay
        ax[3].imshow(
            plot.mask_overlay(
                image[0],
                masks[idx],
            )
        )

        ax[3].set_title("mask overlay")

        plt.tight_layout()
        plt.show()


if __name__ == "__main__":

    # ---------------- initialise file list ----------------

    file_list = [
        filename
        for filename in os.listdir(image_folder)
        if "npy" in filename
    ]

    images_dict = {
        filename.replace(".npy", ""):
        np.load(f"{image_folder}{filename}")
        for filename in file_list
    }

    # ---------------- prepare images ----------------

    # Cellpose-SAM will use the first 3 channels of your image,
    # truncating the rest.
    #
    # It has been trained with the cytoplasm and nuclear channels
    # in any order, with the other channel set to zero.
    #
    # You can combine two stains to create your cytoplasm channel.
    #
    # In this example:
    # indices 0 and 1 contain cellular stains
    # index 2 contains the nuclei

    imgs_cp = [
        np.stack(
            (
                img[[0, 1]].sum(axis=0),
                img[2],
            ),
            axis=0,
        )
        for name, img in images_dict.items()
    ]

    # Other packages can be used to preprocess images and improve
    # segmentation if needed.

    # gaussian_blur = [
    #     filters.gaussian(
    #         image,
    #         sigma=1,
    #         multichannel=True,
    #     )
    #     for image in imgs_cp
    # ]

    # brightened = [
    #     np.clip(
    #         channel * 5,
    #         0,
    #         65535,
    #     ).astype(np.uint16)
    #     for channel in imgs_cp
    # ]

    puncta_blur = [
        np.stack(
            [
                (
                    np.log1p(
                        filters.gaussian(
                            ch.astype(np.float32),
                            sigma=1,
                            preserve_range=True,
                        )
                    )
                    /
                    np.log1p(
                        filters.gaussian(
                            ch.astype(np.float32),
                            sigma=1,
                            preserve_range=True,
                        ).max()
                    )
                    * 65535
                ).astype(np.uint16)

                for ch in img
            ],
            axis=0,
        )

        for img in imgs_cp
    ]

    # Use if trying to create a cytoplasmic signal from a punctate-only
    # channel. This blurs and expands the punctate signal.

    # ---------------- apply cellpose ----------------

    masks, flows, styles = apply_cellpose(
        puncta_blur,
        niter=2000,
        diameter=60,
        big_images=True,
    )

    # Check the masks with visualisation.
    # You can skip this step when running the full dataset.

    visualise_cell_pose(
        puncta_blur[:5],
        masks,
        flows,
        big_images=True,
    )

    # ---------------- save masks ----------------

    image_names = list(images_dict.keys())

    if len(image_names) != len(masks):
        raise RuntimeError(
            f"Number of image names ({len(image_names)}) does not match "
            f"number of masks ({len(masks)})."
        )

    for image_name, mask in zip(image_names, masks):

        mask_path = os.path.join(
            output_folder,
            f"{image_name}_cellmask.npy",
        )

        np.save(
            mask_path,
            mask.astype(np.int32),
        )

        logger.info(
            f"Saved mask: {mask_path} | shape={mask.shape}"
        )

    logger.info("All cell masks saved")